# Generated by Django 5.0.2 on 2024-03-07 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clothe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("shirt", "Shirt"), ("hoodie", "Hoodie")],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="itemsImages")),
                ("price", models.CharField(max_length=30)),
                ("desc", models.CharField(max_length=200)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("black", "Black"),
                            ("green", "Green"),
                            ("red", "Red"),
                            ("blue", "Blue"),
                            ("yellow", "Yellow"),
                            ("orange", "Orange"),
                            ("brown", "Brown"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("extra-large", "Extra-large"),
                        ],
                        max_length=30,
                    ),
                ),
                ("stockCount", models.IntegerField()),
                (
                    "offer",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="No",
                        max_length=30,
                    ),
                ),
                ("old_price", models.CharField(default=0, max_length=30)),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clothe",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("size", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=100, null=True)),
                ("phone", models.CharField(default="", max_length=30)),
                ("order_id", models.CharField(max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Out For Shipping", "Out For Shipping"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=150,
                    ),
                ),
                ("tracking_no", models.CharField(max_length=100, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.clothe"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.CharField(max_length=50)),
                ("quantity", models.IntegerField()),
                (
                    "_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.clothe"
                    ),
                ),
            ],
        ),
    ]
