# Generated by Django 5.0.2 on 2024-02-21 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clothe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="itemsImages")),
                ("price", models.CharField(max_length=10)),
                ("desc", models.CharField(max_length=200)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("white", "Bhite"),
                            ("black", "Black"),
                            ("green", "Green"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("large", "Large"),
                            ("extra-large", "Extra-large"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "offer",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=8
                    ),
                ),
                ("old_price", models.CharField(blank=True, max_length=10)),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clothe",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
