# Generated by Django 5.0.2 on 2024-02-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothe",
            name="color",
            field=models.CharField(
                choices=[("white", "White"), ("black", "Black"), ("green", "Green")],
                max_length=8,
            ),
        ),
    ]
