# Generated by Django 5.0.2 on 2024-02-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_clothe_category_clothe_stockcount_alter_clothe_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothe",
            name="category",
            field=models.CharField(
                choices=[("shirt", "Shirt"), ("hoodie", "Hoodie")], max_length=8
            ),
        ),
    ]
