# Generated by Django 5.0.2 on 2024-02-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_clothe_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothe",
            name="offer",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="No", max_length=8
            ),
        ),
        migrations.AlterField(
            model_name="clothe",
            name="old_price",
            field=models.CharField(default=0, max_length=10),
        ),
    ]
